

services:
  postgres:
    container_name: nest-clean-pg
    image: postgres
    ports:
    - "5444:5444"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest_clean
    volumes:
    - ./data/pg:/data/postgres